# Generated by Django 4.0.5 on 2022-07-04 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssm_app', '0002_alter_song_album_alter_song_playlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_playlists', models.IntegerField()),
                ('max_logins', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default='', upload_to='static/media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='sample',
            field=models.FileField(default='', upload_to='static/sample/'),
            preserve_default=False,
        ),
    ]
