# Generated by Django 4.0.5 on 2022-07-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssm_app', '0007_profile_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pay',
            new_name='payed',
        ),
    ]
