# Generated by Django 4.0.5 on 2022-07-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm_app', '0008_rename_pay_profile_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(blank=True, null=True, to='ssm_app.playlist'),
        ),
    ]
